# -*- coding: utf-8 -*-
"""Simple_APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5UJgqDv0sWYwLZfbhQ-uoMZqxvVCLg0
"""

import streamlit as st

st.title('Meeting App')

# Name input
name = st.text_input('Enter your name')

# Age input
age = st.number_input('Enter your age', min_value=0, max_value=120, step=1)

# Favorite food dropdown
foods = ['Pizza', 'Burger', 'Sushi', 'Pasta', 'Salad']
favorite_food = st.selectbox('Select your favorite food', foods)

# Display entered information
if st.button('Submit'):
    st.write(f'Name: {name}')
    st.write(f'Age: {age}')
    st.write(f'Favorite Food: {favorite_food}')